deployment:
  svc: true 
  bff: true 
  ui: true 

product:
  info:
    data:
      description: "OneCX Help"
      imageUrl: ""
      iconName: "question-circle"
      displayName: "OneCX Help"
      basePath: "/help"  
